name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    uses: tauri-apps/tauri/.github/workflows/release.yml@v2
    with:
      tagName: v__VERSION__
      releaseName: '无情台账机 v__VERSION__'
      releaseBody: 'See the assets to download this version and install.'
      releaseDraft: false
      prerelease: false
